dist: bin
builds:
  - binary: testy2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - mips64le
    flags:
      - -v
    ldflags: |
      -X github.com/prometheus/common/version.Version={{.Version}}
      -X github.com/prometheus/common/version.Revision={{.Commit}}
      -X github.com/prometheus/common/version.Branch={{.Env.APP_BRANCH}}
      -X github.com/prometheus/common/version.BuildUser={{.Env.APP_USER}}@{{.Env.APP_HOST}}
      -X github.com/prometheus/common/version.BuildDate={{.Date}}
release:
  github:
    owner: ribbybibby
    name: testy2
dockers:
  - image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/arm64"
    goarch: arm64
docker_manifests:
  - name_template: "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}"
    image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-amd64"
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-arm64"
  - name_template: "{{.Env.APP_DOCKER_IMAGE_NAME}}:latest"
    image_templates:
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-amd64"
      - "{{.Env.APP_DOCKER_IMAGE_NAME}}:{{.Version}}-arm64"
